import React from 'react'

function Libary() {
  return (
    <div>
      <h1 style={{padding:'20px ', border:'1px solid black',margin:'20px',boxShadow:'0px 0px 10px white' ,backgroundColor:"black",color:'white'}}>Libary</h1>
       <p style={{padding:'20px ', border:'1px solid black',margin:'20px',boxShadow:'0px 0px 10px white' ,backgroundColor:"black",color:'white'}} >Lorem ipsum dolor sit amet consectetur, adipisicing elit. Magnam, sint accusamus cumque accusantium fugit quia perferendis impedit excepturi, at reprehenderit, nisi deserunt eaque quos autem sunt eius neque quibusdam aperiam id eveniet ea sequi. Aliquid eaque labore porro omnis quod aut dicta nesciunt alias reiciendis rerum dolorem dolores, ab quidem dignissimos harum quos dolor soluta laudantium, quam et distinctio ullam reprehenderit? Accusantium, numquam asperiores? Fuga, impedit, ipsam tenetur amet rem pariatur ducimus, optio obcaecati a quisquam eius illo sequi corporis quidem. Deserunt ex, omnis voluptates tenetur provident odit. Vitae numquam est quod delectus error eum? Amet laborum eum nihil neque. Omnis sunt hic sint modi earum expedita perferendis rerum perspiciatis et aut porro cum voluptatibus labore explicabo facilis nostrum iure ipsa ipsum fugit, non rem soluta accusantium. Iure ullam nesciunt sit officiis dolore voluptate cumque quo laborum sapiente repudiandae dolorem eos, assumenda natus autem illum necessitatibus eveniet earum nostrum sed voluptatibus suscipit, animi optio. Laborum, quibusdam veniam ea ut praesentium quia natus, quaerat, animi assumenda expedita laudantium in maxime nulla officia deserunt eveniet at vero reprehenderit ipsum modi porro molestias autem. Perferendis consequatur doloribus nisi officiis, incidunt atque animi illo? Est aliquid accusantium eius assumenda iste odit corrupti laborum nam molestiae dolores sint pariatur doloribus maiores, dolorem id sunt, modi expedita recusandae officiis, tenetur exercitationem ipsum illum inventore esse. Sint rerum nam sit alias tenetur velit explicabo, id a cumque praesentium, repellendus quisquam modi ut voluptate. Quam dignissimos a ipsam quasi, natus nihil eos in dolorem itaque ratione quae quas modi reiciendis alias debitis aperiam porro inventore nisi ipsum optio quaerat iste dolore architecto? Maxime illo ab consectetur ullam fugit ex praesentium provident maiores, accusamus sequi. Recusandae deserunt error, natus molestiae maxime excepturi, quaerat magni quis earum doloribus ipsa inventore alias necessitatibus, fugiat eveniet unde quasi et reiciendis voluptate libero!</p>

        
    </div>
  )
}

export default Libary